'use client';

import React, { useState } from 'react';
import { useAcademicStore } from '../../store/academicStore';
import { User, AcademicMilestoneTrack } from '../../types/academic';
import { 
  X, 
  Mail, 
  Terminal, 
  Eye, 
  Check, 
  AlertTriangle,
  ArrowUpRight
} from 'lucide-react';

interface EmailDigestModalProps {
  studentId: string;
  onClose: () => void;
}

export default function EmailDigestModal({ studentId, onClose }: EmailDigestModalProps) {
  const { users, studentTracks, cards } = useAcademicStore();
  
  const [activeTab, setActiveTab] = useState<'HTML' | 'RAW'>('HTML');
  const [copied, setCopied] = useState(false);

  const student = users.find(u => u.id === studentId);
  const track = studentTracks[studentId];

  if (!student || !track) return null;

  const incompleteMilestone = track.milestones.find(m => m.status !== 'APPROVED');
  const completedMilestonesCount = track.milestones.filter(m => m.status === 'APPROVED').length;
  const totalMilestonesCount = track.milestones.length;

  const studentIncompleteCards = Object.values(cards).filter(c => 
    c.assigneeId === studentId && c.columnId !== 'approved'
  );

  const emailPayload = {
    metadata: {
      engine: 'AURA_VELOCITY_RISK_v1.0',
      timestamp: new Date().toISOString(),
      evaluationDate: '2026-05-24',
      alertLevel: track.overallStatus
    },
    recipient: {
      name: student.name,
      email: student.email,
      role: student.role
    },
    supervisor: {
      name: 'Prof. Arthur Pendelton',
      email: 'a.pendelton@university.edu'
    },
    thesis: {
      title: student.thesisTitle || 'N/A',
      type: track.defenseType
    },
    metrics: {
      requiredVelocity: track.requiredVelocity,
      actualVelocity: track.actualVelocity,
      velocityDeficit: Math.max(0, parseFloat((track.requiredVelocity - track.actualVelocity).toFixed(2))),
      milestonesPassed: `${completedMilestonesCount}/${totalMilestonesCount}`,
      incompleteCardsCount: studentIncompleteCards.length
    },
    triggers: {
      isUnderVelocity: track.actualVelocity < track.requiredVelocity,
      daysSinceLastMovement: 14
    },
    recommendations: [
      'Schedule 1-on-1 progress alignment meeting with advisor.',
      'Refactor blocking tasks in Active Work column into smaller sub-tasks.',
      'Verify that Overleaf drafts are synchronized and DOI metadata keys are filled.'
    ]
  };

  const jsonPayloadString = JSON.stringify(emailPayload, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(jsonPayloadString);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateEmailHtml = () => {
    const isCritical = track.overallStatus === 'CRITICAL_STAGNATION';
    const isAtRisk = track.overallStatus === 'AT_RISK';
    const statusColor = isCritical ? '#ef4444' : isAtRisk ? '#f59e0b' : '#10b981';
    const statusBg = isCritical ? '#fef2f2' : isAtRisk ? '#fffbeb' : '#ecfdf5';
    
    return `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; background-color: #ffffff; color: #1e293b;">
        <div style="background-color: #1e1b4b; padding: 24px; text-align: center; border-bottom: 3px solid ${statusColor};">
          <h1 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 700; letter-spacing: -0.025em;">AURA LABS RISK ENGINE</h1>
          <p style="color: #a5b4fc; margin: 4px 0 0 0; font-size: 12px; font-family: monospace;">AUTOMATED progression digest &amp; alert</p>
        </div>
        <div style="background-color: ${statusBg}; padding: 16px; border-bottom: 1px solid #e2e8f0; text-align: center;">
          <span style="font-size: 11px; text-transform: uppercase; font-weight: 800; letter-spacing: 0.05em; color: ${statusColor}; display: block; margin-bottom: 4px;">Status Alert Level</span>
          <span style="font-size: 16px; font-weight: 800; color: ${statusColor}; text-transform: uppercase; font-family: monospace;">
            ${track.overallStatus.replace('_', ' ')}
          </span>
        </div>
        <div style="padding: 24px; line-height: 1.5; font-size: 14px;">
          <p style="margin-top: 0;">Dear <strong>${student.name}</strong>,</p>
          <p>This is an automated progress evaluation report generated by the AURA supervision engine.</p>
          <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin: 20px 0;">
            <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
              <tr><td style="padding: 4px 0; color: #64748b;">Target Graduation:</td><td style="padding: 4px 0; font-weight: 600; text-align: right; font-family: monospace;">${track.targetGraduationWindow}</td></tr>
              <tr><td style="padding: 4px 0; color: #64748b;">Milestones passed:</td><td style="padding: 4px 0; font-weight: 700; text-align: right; color: #1e1b4b;">${completedMilestonesCount} of ${totalMilestonesCount} passed</td></tr>
              <tr><td style="padding: 4px 0; color: #64748b;">Required Velocity:</td><td style="padding: 4px 0; font-weight: 700; text-align: right; font-family: monospace; color: #4f46e5;">${track.requiredVelocity} cards/week</td></tr>
              <tr><td style="padding: 4px 0; color: #64748b;">Actual Velocity:</td><td style="padding: 4px 0; font-weight: 700; text-align: right; font-family: monospace; color: ${track.actualVelocity >= track.requiredVelocity ? '#10b981' : '#ef4444'};">${track.actualVelocity} cards/week</td></tr>
            </table>
          </div>
          <h3 style="font-size: 13px; font-weight: 700; margin: 20px 0 8px 0; text-transform: uppercase; letter-spacing: 0.05em; color: #475569;">Incomplete Tasks (${studentIncompleteCards.length})</h3>
          <ul style="margin: 0; padding-left: 20px; font-size: 13px; color: #334155;">
            ${studentIncompleteCards.map(c => `<li style="margin-bottom: 6px;"><strong>[${c.priority}]</strong> ${c.title}</li>`).join('')}
          </ul>
        </div>
        <div style="background-color: #f1f5f9; padding: 16px; text-align: center; border-top: 1px solid #e2e8f0; font-size: 11px; color: #64748b;">
          This is an automated notification from AURA supervision engine.
        </div>
      </div>
    `;
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-[var(--bg-primary)] border border-[var(--border-primary)] rounded-lg max-w-2xl w-full max-h-[90vh] overflow-hidden flex flex-col shadow-2xl glow-accent animate-in fade-in duration-200">
        <div className="p-3 border-b border-[var(--border-primary)] bg-[var(--bg-secondary)] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Mail className="w-4 h-4 text-[var(--accent)]" />
            <h3 className="text-xs font-bold text-[var(--text-primary)] font-mono uppercase tracking-wide">
              Email Digest Alert Payload Constructor
            </h3>
          </div>
          <button onClick={onClose} className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="px-3 py-2 bg-[var(--bg-primary)] border-b border-[var(--border-primary)] flex items-center justify-between gap-4">
          <div className="flex bg-[var(--bg-tertiary)] rounded p-0.5">
            <button
              onClick={() => setActiveTab('HTML')}
              className={`px-3 py-1 rounded text-[10px] font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'HTML' ? 'bg-[var(--bg-primary)] text-[var(--accent)] shadow-sm' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
            >
              <Eye className="w-3.5 h-3.5" /> HTML Preview
            </button>
            <button
              onClick={() => setActiveTab('RAW')}
              className={`px-3 py-1 rounded text-[10px] font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'RAW' ? 'bg-[var(--bg-primary)] text-[var(--accent)] shadow-sm' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
            >
              <Terminal className="w-3.5 h-3.5" /> JSON Payload
            </button>
          </div>
          {activeTab === 'RAW' && (
            <button
              onClick={handleCopy}
              className="bg-[var(--accent-bg)] text-[var(--accent)] border border-[var(--accent)]/30 hover:bg-[var(--accent)] hover:text-white px-2.5 py-1 rounded text-[9px] font-bold transition-all cursor-pointer flex items-center gap-1 shadow-sm"
            >
              {copied ? <><Check className="w-3 h-3" /> Copied!</> : 'Copy JSON'}
            </button>
          )}
        </div>

        <div className="flex-1 overflow-y-auto p-4 bg-[var(--bg-secondary)]">
          {activeTab === 'HTML' ? (
            <div className="bg-white border rounded p-4 shadow-inner max-w-full overflow-x-auto text-[13px] leading-normal text-black font-sans">
              <div dangerouslySetInnerHTML={{ __html: generateEmailHtml() }} />
            </div>
          ) : (
            <div className="relative">
              <pre className="bg-neutral-900 text-neutral-200 border border-neutral-800 rounded p-3 text-[10px] font-mono leading-relaxed overflow-x-auto select-all max-h-[50vh]">
                {jsonPayloadString}
              </pre>
            </div>
          )}
        </div>

        <div className="p-3 border-t border-[var(--border-primary)] bg-[var(--bg-secondary)] text-[10px] text-[var(--text-tertiary)] flex gap-2">
          <AlertTriangle className="w-4 h-4 text-[var(--accent)] shrink-0 mt-0.5" />
          <span>
            <strong>Alert Digest Payload:</strong> This telemetry block is queued by AURA's scheduler daily. If a student falls below critical velocity thresholds, the JSON payload is dispatched to the laboratory SMTP relay worker.
          </span>
        </div>
      </div>
    </div>
  );
}
